#pragma once

enum OBJID { OBJ_IBB, OBJ_OBB, OBJ_MONSTER, OBJ_TRACK, OBJ_HOLE, OBJ_IHOLE, OBJ_OHOLE, OBJ_JUMP, OBJ_MAPRECT, OBJ_BACKOBJ, OBJ_SUPPORT, OBJ_COIN, OBJ_EFFECT, OBJ_END };

//enum RENDEROBJID { RD_TRACK, RD_SUPPORT, RD_MAPRECT, RD_BACKOBJ, RD_END };

enum TEXTYPE { TEX_SINGLE,TEX_MULTI, TEX_END };

enum SCENEID { SC_LOGO, SC_MENU, SC_GAME, SC_END };

enum RECTTYPE { RT_TRACK, RT_HOLE, RT_IHOLE, RT_OHOLE, RT_JUMP, RT_END };

enum BACKTYPE { BG_FIX, BG_MOV, BG_END };

enum MONSTERTYPE { MT_CIR, MT_HALF, MT_END };

enum SUPPORTTYPE { SP_RT, SP_PARA, SP_LONG, SP_END };

enum CHANNELID { CHANNEL_BGM, CHANNEL_PLAYER, CHANNEL_MONSTER, CHANNEL_EFFECT, CHANNEL_END };

enum CHARACTERID { CHAR_IBB, CHAR_OBB, CHAR_END };